fix

diff --git a/.github/workflows/build-verify.yml b/.github/workflows/build-verify.yml
--- a/.github/workflows/build-verify.yml
+++ b/.github/workflows/build-verify.yml
@@ -43,7 +43,4 @@ jobs:
         cd Samples/Scratchpad/scratchpad_c
         cmake .
         make
-		if ! ./scratchpad_c; then
-		  echo "[error] Running ./scratchpad_c failed. This indicates the C code being generated is not producing the expected values."
-		  exit 1
-		fi
+		./scratchpad_c || { echo "[error] Running ./scratchpad_c failed. This indicates the C code being generated is not producing the expected values."; exit 1; }
